safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
highlighter: rouge
markdown: kramdown
exclude: ['.git', '.travis.yml', '.travis.d', '.sass-cache', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'LICENSE.md', '.asset-cache', 'Dockerfile', '_scripts', 'vendor/']
encoding: utf-8

plugins:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-last-modified-at

url: https://conext-21-iwci.named-data.net
baseurl:

# Configuration for site
title: CoNEXT 2021 Interdisciplinary Workshop on (de)Centralization in the Internet (IWCI)
logo:
  image: tbd.jpg
  info: Virtual

# Google Analytics tracking
# google_analytics_id: 

#program:
  # If the specified file doesn't exist, there will be command-line dialog to create it
  # (Currently hardcoded for a dummy robot.mcrobot.jr@gmail.com account permissions)
#  google_client_id: .travis.d/google_client_id.json
  # Google spreadsheet with the conference data
#  spreadsheet: 

#program-at-glance:
#  google_client_id: .travis.d/google_client_id.json
#  spreadsheet:
#    - 
  
assets:
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower
    - _assets/misc
    - _assets/files
    - .sass-cache

  plugins:
    css:
      autoprefixer:
        browsers:
          - "last 2 versions"
          - "IE > 9"

    img: { optim: {}, magick: {} }
